# Desktiptive Maße I

## Daten
```{r reading_XML, highlight = TRUE, results = 'hide', echo = TRUE, cache = TRUE}
library(XML)

tokens <- vector('character')
types <- vector('character')

xmlEventParse(
  "../data/t_990505_47.xml", 
  handlers = list(
    't' = function(name, attr) {
      tokens <<- c(tokens, attr['word'])
      types <<- c(types, attr['lemma'])
      ## morphology
      }
    ),
  addContext = FALSE
  )

#raw.token.lengths <- nchar(tokens)
# names(tokens) <- NULL
tokens <- unname(tokens)
token.lengths <- nchar(tokens)

```

```{r}
length(tokens)
```

## Wörter auswählen

```{r choose_words, echo = T}
tokens[nchar(tokens) == 22]
```

```{r}
#raw.token.lengths
```

## Modus
```{r mode, echo = T}
mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

#token.lengths
t1 <- table(token.lengths)
t1 
mode(token.lengths)
```

## Arbeit mit Tabellen
```{r tables, echo = T}
summary(t1)
t1[1]
dimnames(t1)
dim(t1)
```

## Median
```{r median, echo = T}
median(token.lengths)
length(token.lengths)
head(sort(token.lengths), length(token.lengths)/2)
t2 <- prop.table(table(token.lengths))
cumsum(t2)
```

```{r descriptive_values, echo = T}
mode(token.lengths)
median(token.lengths)
mean(token.lengths)

```
```{r}
hist(token.lengths)
```

```{r symmetric_data, echo = T}
set.seed(12)
normal.sample <- rnorm(100)
mode(normal.sample)
median(normal.sample)
mean(normal.sample)
```


## Quantile
```{r quantile, echo = T}
#quantile()
```

## Treppenfunktionen
```{r, functionplot, echo = T}

plot(cumsum(t2), type = 'S')

```

## Aufgaben

* Deskriptive Werte für die Types berechnen (wie für Tokens bereits gemacht)
* Werte tabellarisch mit Fall, Häufigkeit, relative Häufigkeit, Summenhäufigkeit, relative Summenhäufigkeit darstellen
